apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: gitsaktechkong
  namespace: kong
spec:
  rules:
  - host: ken-ubuntu.saksiam.corp
    http:
      paths:
      - backend:
          service:
            name: gitsaktechkong
            port:
              number: 8080
        path: /gitsaktechkong/
        pathType: Prefix
status:
  loadBalancer: {}
